# Generated by Django 6.1 on 2026-08-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('course', 'دورة'), ('workshop', 'ورشة'), ('conference', 'مؤتمر'), ('seminar', 'ندوة')], default='course', max_length=30)),
                ('status', models.CharField(choices=[('available', 'متاح'), ('cancelled', 'ملغي')], default='available', max_length=20)),
            ],
        ),
    ]
