# Generated by Django 6.0.7 on 2026-08-13 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(choices=[('sanaa', 'صنعاء'), ('aden', 'عدن'), ('taiz', 'تعز'), ('ibb', 'إب'), ('hodeidah', 'الحديدة'), ('hadramout', 'حضرموت')], default='sanaa', max_length=30),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('onsite', 'حضوري'), ('online', 'أونلاين'), ('hybrid', 'مختلط')], default='onsite', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('available', 'متاح'), ('full', 'مكتمل'), ('cancelled', 'ملغي')], default='available', max_length=20),
        ),
    ]
